# Read the Docs configuration file
version: 2

# Set OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx and configuration file
sphinx:
  configuration: docs/conf.py

# Build additional formats
formats:
   - pdf

# Specify python version for build
python:
   install:
   - requirements: docs/requirements.txt